# Generated by Django 4.2 on 2025-03-06 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="HealthPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("plan_details", models.TextField()),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("blood_glucose", "Blood Glucose"),
                            ("pulse_rate", "Pulse Rate"),
                            ("blood_pressure", "Blood Pressure"),
                            ("cholesterol", "Cholesterol"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        max_length=10,
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="health_plans",
                        to="users.userprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EHR",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("visits", models.IntegerField(default=0)),
                ("medications", models.TextField(blank=True)),
                ("lab_results", models.TextField(blank=True)),
                ("vaccinations", models.TextField(blank=True)),
                ("report_id", models.CharField(max_length=20, unique=True)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ehr_records",
                        to="users.userprofile",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="ehr",
            index=models.Index(fields=["patient"], name="ehr_ehr_patient_6ab043_idx"),
        ),
        migrations.AddIndex(
            model_name="ehr",
            index=models.Index(fields=["report_id"], name="ehr_ehr_report__799c18_idx"),
        ),
    ]
