version: '3.8'

services:
  web:
    build: .
    restart: always
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    ports:
      - "8000:8000"
    networks:
      - healthcare_network

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    networks:
      - healthcare_network

  nginx:
    image: nginx:1.21
    restart: always
    depends_on:
      - web
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - static_volume:/var/www/html/static
      - media_volume:/var/www/html/media
    networks:
      - healthcare_network

networks:
  healthcare_network:

volumes:
  postgres_data:
  static_volume:
  media_volume:
