# Generated by Django 4.2 on 2025-03-07 22:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="metadata",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
