# Generated by Django 4.2 on 2025-03-08 10:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_userprofile_profile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="healthcare_provider_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("doctor", "Doctor"),
                    ("nurse", "Nurse"),
                    ("admin", "Admin"),
                    ("clinic", "Clinic/Hospital"),
                ],
                max_length=10,
                null=True,
            ),
        ),
    ]
