# Generated by Django 4.2 on 2025-03-06 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("report_id", models.CharField(max_length=20, unique=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("genomic", "Genomic"),
                            ("clinical", "Clinical"),
                            ("patient", "Patient"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("done", "Done"),
                            ("waiting_approval", "Waiting Approval"),
                        ],
                        max_length=20,
                    ),
                ),
                ("date", models.DateField()),
                ("content", models.TextField()),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="users.userprofile",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="report",
            index=models.Index(
                fields=["report_id"], name="reports_rep_report__228034_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="report",
            index=models.Index(
                fields=["patient"], name="reports_rep_patient_c642a7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="report",
            index=models.Index(fields=["type"], name="reports_rep_type_0f10af_idx"),
        ),
        migrations.AddIndex(
            model_name="report",
            index=models.Index(fields=["status"], name="reports_rep_status_c732ef_idx"),
        ),
    ]
